apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "emx2.fullname" . }}
  labels:
    app: {{ template "emx2.name" . }}
    chart: {{ template "emx2.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "emx2.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "emx2.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Chart.Name }}
          imagePullPolicy: Always
          env:
            - name: jdbc
              value: jdbc:postgresql:molgenis
          ports:
            - containerPort: 8080
          env:
            - name: MOLGENIS_ADMIN_PW
              valueFrom:
                secretKeyRef:
                  name: {{ template "emx2.fullname" $ }}
                  key: adminpassword
        - image: postgres:11-alpine
          name: postgres
          args:
            - -c
            - shared_buffers=256MB
            - -c
            - max_locks_per_transaction=1024
          env:
            - name: POSTGRES_DB
              value: molgenis
            - name: POSTGRES_PASSWORD
              value: molgenis
            - name: POSTGRES_USER
              value: molgenis
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv
      volumes:
        - name: postgres-pv
          persistentVolumeClaim:
            claimName: {{ include "emx2.fullname" . }}-postgres-pv
      restartPolicy: Always
status: {}
